# Generated by Django 4.2.7 on 2023-11-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todoitem',
            new_name='Task',
        ),
    ]
